# Generated by Django 3.2.8 on 2021-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='color_gist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
