# Generated by Django 3.2.8 on 2021-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_features_color_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url_path',
            field=models.CharField(default='DEFAULT VALUE', max_length=512),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=512, primary_key=True, serialize=False),
        ),
    ]
