# Generated by Django 3.2.8 on 2021-11-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_predict_option_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.BigIntegerField(blank=True, null=True)),
                ('width', models.BigIntegerField(blank=True, null=True)),
                ('nchannels', models.BigIntegerField(blank=True, db_column='nChannels', null=True)),
                ('mode', models.BigIntegerField(blank=True, null=True)),
                ('sift', models.TextField(blank=True, null=True)),
                ('color_moments', models.TextField(blank=True, null=True)),
                ('color_gist', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.prediction')),
            ],
        ),
    ]
