# Generated by Django 3.2.8 on 2021-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_predict_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_option',
            name='url_path',
            field=models.CharField(default='DEFAULT VALUE', max_length=512),
        ),
    ]
