# Generated by Django 3.2.8 on 2021-11-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20211129_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict_features',
            name='image',
        ),
        migrations.AddField(
            model_name='predict_features',
            name='image_id',
            field=models.CharField(default='DEFAULT VALUE', max_length=512),
        ),
    ]
